"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["entrypoints_inspector_main_nodeIcon_css_js"], {
"./entrypoints/inspector_main/nodeIcon.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2017 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.node-icon {\n  width: 28px;\n  height: 26px;\n  background-image: var(--image-file-nodeIcon);\n  background-size: 17px 17px;\n  background-repeat: no-repeat;\n  background-position: center;\n  opacity: 80%;\n  cursor: auto;\n}\n\n.node-icon:hover {\n  opacity: 100%;\n}\n\n.node-icon.inactive {\n  filter: grayscale(100%);\n}\n\n/*# sourceURL=nodeIcon.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);