"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_application_components_interestGroupAccessGrid_css_js"], {
"./panels/application/components/interestGroupAccessGrid.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright (c) 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n:host {\n  padding: 20px;\n}\n\n.heading {\n  font-size: 15px;\n}\n\ndevtools-data-grid-controller {\n  border: 1px solid var(--sys-color-divider);\n  margin-top: 20px;\n}\n\n.info-icon {\n  vertical-align: text-bottom;\n  height: 14px;\n}\n\n.no-events-message {\n  margin-top: 20px;\n}\n\n/*# sourceURL=interestGroupAccessGrid.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);