"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_elements_layersWidget_css_js"], {
"./panels/elements/layersWidget.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/**\n * Copyright 2022 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.styles-layers-pane {\n  overflow: hidden;\n  padding-left: 2px;\n  background-color: var(--sys-color-cdt-base-container);\n  border-bottom: 1px solid var(--sys-color-divider);\n  margin-top: 0;\n  padding-bottom: 2px;\n}\n\n.styles-layers-pane > div {\n  font-weight: bold;\n  margin: 8px 4px 6px;\n}\n\n.styles-layers-pane > table {\n  width: 100%;\n  border-spacing: 0;\n}\n\n.styles-layers-pane td {\n  padding: 0;\n}\n\n/*# sourceURL=layersWidget.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);