"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_elements_components_stylePropertyEditor_css_js"], {
"./panels/elements/components/stylePropertyEditor.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.container {\n  padding: 12px;\n  min-width: 170px;\n}\n\n.row {\n  padding: 0;\n  color: var(--sys-color-on-surface);\n  padding-bottom: 16px;\n}\n\n.row:last-child {\n  padding-bottom: 0;\n}\n\n.property {\n  padding-bottom: 4px;\n  white-space: nowrap;\n}\n\n.property-name {\n  color: var(--sys-color-token-property-special);\n}\n\n.property-value {\n  color: var(--sys-color-on-surface);\n}\n\n.property-value.not-authored {\n  color: var(--sys-color-state-disabled);\n}\n\n.buttons {\n  display: flex;\n  flex-direction: row;\n}\n\n.buttons > :first-child {\n  border-radius: 3px 0 0 3px;\n}\n\n.buttons > :last-child {\n  border-radius: 0 3px 3px 0;\n}\n\n.button {\n  border: 1px solid var(--sys-color-neutral-outline);\n  background-color: var(--sys-color-cdt-base-container);\n  width: 24px;\n  height: 24px;\n  min-width: 24px;\n  min-height: 24px;\n  padding: 0;\n  margin: 0;\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  cursor: pointer;\n}\n\n.button:focus-visible {\n  outline: auto 5px -webkit-focus-ring-color;\n}\n\n.button devtools-icon {\n  color: var(--icon-default);\n}\n\n.button:hover devtools-icon {\n  color: var(--icon-default-hover);\n}\n\n.button.selected devtools-icon {\n  color: var(--icon-toggled);\n}\n\n/*# sourceURL=stylePropertyEditor.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);