"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_network_requestHTMLView_css_js"], {
"./panels/network/requestHTMLView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright (c) 2018 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.html-preview-frame {\n  box-shadow: var(--drop-shadow);\n  /* We always want a white background, even in dark mode */\n  background: var(--ref-palette-neutral100);\n  flex-grow: 1;\n  margin: 20px;\n}\n\n/*# sourceURL=requestHTMLView.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);