"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_issues_components_hideIssuesMenu_css_js"], {
"./panels/issues/components/hideIssuesMenu.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.hide-issues-menu-btn {\n  position: relative;\n  display: flex;\n  background-color: transparent;\n  flex: none;\n  align-items: center;\n  justify-content: center;\n  padding: 0;\n  margin: 0 -2px 0 4px;\n  overflow: hidden;\n  border-radius: 0;\n  border: none;\n\n  &:hover > devtools-icon {\n    color: var(--icon-default-hover);\n  }\n}\n\n/*# sourceURL=./hideIssuesMenu.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);