"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_media_playerMessagesView_css_js"], {
"./panels/media/playerMessagesView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2020 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n.media-messages-header {\n  background-color: var(--sys-color-cdt-base-container);\n  border-bottom: 1px solid var(--sys-color-divider);\n  min-height: 26px;\n}\n\n.media-messages-body {\n  overflow-y: scroll;\n}\n\n.media-messages-level-dropdown-element {\n  height: 18px;\n  line-height: 18px;\n}\n\n.media-messages-level-dropdown-text {\n  float: left;\n}\n\n.media-messages-level-dropdown-checkbox {\n  float: left;\n  width: 18px;\n  height: 100%;\n  padding-left: 2px;\n}\n\n.media-messages-message-container {\n  margin: 4px;\n  font-size: 14px;\n  line-height: 18px;\n  padding: 4px;\n  user-select: text;\n}\n\n.media-messages-message-container + .media-messages-message-container {\n  border-top: 1px solid var(--sys-color-divider);\n\n  &.media-message-warning,\n  &.media-message-error {\n    border: none;\n  }\n}\n\n.media-message-warning {\n  border-radius: 5px;\n  background-color: var(--sys-color-surface-yellow);\n  color: var(--sys-color-on-surface-yellow);\n}\n\n.media-message-error {\n  border-radius: 5px;\n  background-color: var(--sys-color-surface-error);\n  color: var(--sys-color-on-surface-error);\n}\n\n.media-messages-message-filtered {\n  display: none;\n}\n\n.media-messages-message-unselected {\n  display: none;\n}\n\n.status-error-box {\n  font-family: monospace;\n  border: 1px solid var(--sys-color-error-outline);\n  border-radius: 5px;\n  padding: 4px;\n}\n\n.status-error-field-label {\n  padding-right: 10px;\n  color: var(--sys-color-token-subtle);\n}\n\n.status-error-field-labeled {\n  display: flex;\n}\n\n/*# sourceURL=playerMessagesView.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);