"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_application_components_permissionsPolicySection_css_js"], {
"./panels/application/components/permissionsPolicySection.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright (c) 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  display: contents;\n}\n\n.text-ellipsis {\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n}\n\n.link,\n.devtools-link {\n  color: var(--sys-color-primary);\n  text-decoration: underline;\n  cursor: pointer;\n  outline-offset: 2px;\n}\n\nbutton.link {\n  border: none;\n  background: none;\n  font-family: inherit;\n  font-size: inherit;\n}\n\n.policies-list {\n  padding-top: 3px;\n}\n\n.permissions-row {\n  display: flex;\n  line-height: 22px;\n}\n\n.permissions-row div {\n  padding-right: 5px;\n}\n\n.feature-name {\n  width: 135px;\n}\n\n.allowed-icon {\n  vertical-align: sub;\n}\n\n.block-reason {\n  width: 215px;\n}\n\n/*# sourceURL=permissionsPolicySection.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);