"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_css_overview_cssOverviewSidebarPanel_css_js"], {
"./panels/css_overview/cssOverviewSidebarPanel.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/**\n * Copyright 2019 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.overview-sidebar-panel {\n  overflow: auto;\n  display: flex;\n  background: var(--sys-color-cdt-base-container);\n}\n\n.overview-sidebar-panel-container {\n  min-width: fit-content;\n}\n\n.overview-sidebar-panel-item {\n  height: 30px;\n  padding-left: 30px;\n  display: flex;\n  align-items: center;\n  color: var(--sys-color-on-surface);\n  white-space: nowrap;\n\n  &:hover {\n    background: var(--sys-color-state-hover-on-subtle);\n  }\n\n  &:focus {\n    background: var(--sys-color-state-focus-highlight);\n  }\n\n  &.selected {\n    background: var(--sys-color-tonal-container);\n    color: var(--sys-color-on-tonal-container);\n  }\n}\n\n.overview-toolbar {\n  border-bottom: 1px solid var(--sys-color-divider);\n  flex: 0 0 auto;\n}\n\n.overview-sidebar-panel-item:focus-visible {\n  outline-width: unset;\n}\n\n@media (forced-colors: active) {\n  .overview-sidebar-panel-item.selected {\n    forced-color-adjust: none; /* crbug.com/1166705 workaround */\n    background: Highlight;\n    color: HighlightText;\n  }\n\n  .overview-sidebar-panel-item:hover {\n    forced-color-adjust: none; /* crbug.com/1166705 workaround */\n    background: Highlight;\n    color: HighlightText;\n  }\n}\n\n/*# sourceURL=cssOverviewSidebarPanel.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);