"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_security_lockIcon_css_js"], {
"./panels/security/lockIcon.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2015 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.lock-icon,\n.security-property {\n  height: var(--sys-size-9);\n  width: var(--sys-size-9);\n}\n\n.lock-icon-secure {\n  color: var(--sys-color-green);\n}\n\n.lock-icon-insecure {\n  color: var(--sys-color-error);\n}\n\n.lock-icon-insecure-broken {\n  color: var(--sys-color-error);\n}\n\n.security-property-secure {\n  color: var(--sys-color-green);\n}\n\n.security-property-neutral {\n  color: var(--sys-color-error);\n}\n\n.security-property-insecure {\n  color: var(--sys-color-error);\n}\n\n.security-property-insecure-broken {\n  color: var(--sys-color-error);\n}\n\n.security-property-info {\n  color: var(--sys-color-on-surface-subtle);\n}\n\n.security-property-unknown {\n  color: var(--sys-color-on-surface-subtle);\n}\n\n.url-scheme-secure {\n  color: var(--sys-color-green);\n}\n\n.url-scheme-neutral,\n.url-scheme-insecure,\n.url-scheme-insecure-broken {\n  color: var(--sys-color-error);\n}\n\n/*# sourceURL=lockIcon.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);