"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_application_appManifestView_css_js"], {
"./panels/application/appManifestView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync('/*\n * Copyright 2016 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n.report-field-name {\n  flex-basis: 152px;\n}\n\n.manifest-view-header {\n  min-width: 600px;\n  flex-shrink: 0;\n  flex-grow: 0;\n}\n\n.manifest-container {\n  overflow: auto;\n}\n\n.inline-icon {\n  margin-inline: 4px;\n  width: 16px;\n  height: 16px;\n\n  &[name="check-circle"] {\n    color: var(--icon-checkmark-green);\n  }\n}\n\n.multiline-value {\n  white-space: normal;\n}\n\n.chrome-select {\n  margin: 4px;\n}\n\n.inline-button {\n  vertical-align: sub;\n}\n\n/*# sourceURL=appManifestView.css */\n');
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);