"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_browser_debugger_xhrBreakpointsSidebarPane_css_js"], {
"./panels/browser_debugger/xhrBreakpointsSidebarPane.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync('/*\n * Copyright 2017 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.breakpoint-list {\n  padding-bottom: 3px;\n}\n\n.breakpoint-list .editing.being-edited {\n  overflow: hidden;\n  white-space: nowrap;\n}\n\n.breakpoint-condition {\n  display: block;\n  margin: 4px 8px 4px 23px;\n}\n\n.breakpoint-condition-input {\n  display: block;\n  margin-left: 0;\n  margin-right: 0;\n  border: 1px solid var(--sys-color-neutral-outline);\n  border-radius: 4px;\n\n  &:focus {\n    outline: 5px auto var(--sys-color-tonal-outline);\n    box-shadow: none;\n  }\n}\n\n.breakpoint-entry {\n  white-space: nowrap;\n  padding: 2px 0;\n}\n\n.breakpoint-list .breakpoint-entry:focus-visible {\n  background-color: var(--sys-color-tonal-container);\n}\n\n.breakpoint-entry [is="dt-checkbox"] {\n  max-width: 100%;\n}\n\n.breakpoint-hit {\n  background-color: var(--sys-color-yellow-container);\n  border-right: 3px solid var(--sys-color-yellow-outline);\n  color: var(--sys-color-on-yellow-container);\n}\n\n@media (forced-colors: active) {\n  .breakpoint-list .breakpoint-entry:hover,\n  .breakpoint-list .breakpoint-entry:focus-visible {\n    forced-color-adjust: none;\n    background-color: Highlight;\n  }\n\n  .breakpoint-list .breakpoint-entry:hover *,\n  .breakpoint-list .breakpoint-entry:focus-visible * {\n    color: HighlightText;\n  }\n}\n\n/*# sourceURL=xhrBreakpointsSidebarPane.css */\n');
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);