"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_accessibility_accessibilityProperties_css_js"], {
"./panels/accessibility/accessibilityProperties.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2015 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.ax-name {\n  color: var(--sys-color-token-attribute);\n  flex-shrink: 0;\n}\n\n.ax-readable-name {\n  flex-shrink: 0;\n}\n\n.ax-readable-string {\n  font-style: italic;\n}\n\n.ax-value-string {\n  color: var(--sys-color-token-property-special);\n}\n\nspan.ax-internal-role {\n  font-style: italic;\n}\n\n#source-order-warning {\n  padding-bottom: 0;\n  text-align: left;\n}\n\n.source-order-checkbox {\n  margin: 2px 2px 2px 5px;\n}\n\n/*# sourceURL=accessibilityProperties.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);