"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_recorder_components_extensionView_css_js"], {
"./panels/recorder/components/extensionView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2023 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n* {\n  margin: 0;\n  padding: 0;\n  outline: none;\n  box-sizing: border-box;\n  font-size: inherit;\n}\n\n.extension-view {\n  display: flex;\n  flex-direction: column;\n  height: 100%;\n}\n\nmain {\n  flex: 1;\n}\n\niframe {\n  border: none;\n  height: 100%;\n  width: 100%;\n}\n\nheader {\n  display: flex;\n  padding: 3px 8px;\n  justify-content: space-between;\n  border-bottom: 1px solid var(--sys-color-divider);\n}\n\nheader > div {\n  align-self: center;\n}\n\n.icon {\n  display: block;\n  width: 16px;\n  height: 16px;\n  color: var(--sys-color-secondary);\n}\n\n.title {\n  display: flex;\n  flex-direction: row;\n  gap: 6px;\n  color: var(--sys-color-secondary);\n  align-items: center;\n  font-weight: 500;\n}\n\n/*# sourceURL=extensionView.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);