"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_application_components_frameDetailsReportView_css_js"], {
"./panels/application/components/frameDetailsReportView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync('/*\n * Copyright (c) 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.text-ellipsis {\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n}\n\nbutton ~ .text-ellipsis {\n  padding-left: 2px;\n}\n\n.link,\n.devtools-link {\n  color: var(--sys-color-primary);\n  text-decoration: underline;\n  cursor: pointer;\n  outline-offset: 2px;\n  padding: 0;\n}\n\nbutton.link {\n  border: none;\n  background: none;\n  font-family: inherit;\n  font-size: inherit;\n  height: 16px;\n}\n\nbutton.link:has(devtools-icon) {\n  margin-top: 5px;\n}\n\ndevtools-button.help-button {\n  top: 4px;\n  position: relative;\n}\n\nbutton.text-link {\n  padding-left: 2px;\n  height: 26px;\n}\n\n.inline-button {\n  padding-left: 1ex;\n}\n\n.inline-comment {\n  padding-left: 1ex;\n  white-space: pre-line;\n}\n\n.inline-comment::before {\n  content: "(";\n}\n\n.inline-comment::after {\n  content: ")";\n}\n\n.inline-name {\n  color: var(--sys-color-token-subtle);\n  padding-right: 4px;\n  user-select: none;\n  white-space: pre-line;\n}\n\n.inline-items {\n  display: flex;\n}\n\n.span-cols {\n  grid-column-start: span 2;\n  margin: 0 0 8px 30px;\n  line-height: 28px;\n}\n\n.without-min-width {\n  min-width: auto;\n}\n\n.bold {\n  font-weight: bold;\n}\n\n.link:not(button):has(devtools-icon) {\n  vertical-align: baseline;\n  margin-inline-start: 3px;\n}\n\n.inline-icon {\n  margin-bottom: -5px;\n  width: 18px;\n  height: 18px;\n  vertical-align: baseline;\n}\n\n@media (forced-colors: active) {\n  .link,\n  .devtools-link {\n    color: linktext;\n    text-decoration-color: linktext;\n  }\n}\n\n/*# sourceURL=frameDetailsReportView.css */\n');
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);