"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_coverage_coverageListView_css_js"], {
"./panels/coverage/coverageListView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.data-grid {\n  border: none;\n}\n\n.data-grid td .url-outer {\n  width: 100%;\n  display: inline-flex;\n  justify-content: flex-start;\n}\n\n.data-grid td .url-outer .filter-highlight {\n  font-weight: bold;\n}\n\n.data-grid td .url-prefix {\n  overflow-x: hidden;\n  text-overflow: ellipsis;\n}\n\n.data-grid td .url-suffix {\n  flex: none;\n}\n\n.data-grid td .bar {\n  display: inline-block;\n  height: 8px;\n  border: 1px solid transparent;\n}\n\n.data-grid td .bar-unused-size {\n  background-color: var(--app-color-coverage-unused);\n}\n\n.data-grid td .bar-used-size {\n  background-color: var(--app-color-coverage-used);\n}\n\n.data-grid td .percent-value {\n  width: 7ex;\n  display: inline-block;\n  color: var(--sys-color-on-surface-subtle);\n}\n\n@media (forced-colors: active) {\n  .data-grid td .bar-container {\n    forced-color-adjust: none;\n  }\n\n  .data-grid td .bar-unused-size {\n    background-color: ButtonText;\n  }\n\n  .data-grid td .bar-used-size {\n    background-color: ButtonFace;\n  }\n\n  .data-grid td .bar {\n    border-color: ButtonText;\n  }\n\n  .data-grid .selected td .bar {\n    border-top-color: HighlightText;\n    border-bottom-color: HighlightText;\n  }\n\n  .data-grid .selected td .bar:last-child {\n    border-right-color: HighlightText;\n  }\n\n  .data-grid .selected td .bar:first-child {\n    border-left-color: HighlightText;\n  }\n\n  .data-grid:focus tr.selected span.percent-value {\n    color: HighlightText;\n  }\n}\n\n/*# sourceURL=coverageListView.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);