"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_sources_dialog_css_js"], {
"./panels/sources/dialog.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync('/*\n * Copyright (c) 2015 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  padding: 10px;\n}\n\n.widget {\n  align-items: center;\n}\n\nlabel {\n  white-space: nowrap;\n}\n\ninput[type="text"].add-source-map {\n  box-shadow: 0 0 0 1px var(--box-shadow-outline-color);\n  font-size: inherit;\n  margin: 0 8px 0 5px;\n}\n\n/*# sourceURL=dialog.css */\n');
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);