"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_sources_scopeChainSidebarPane_css_js"], {
"./panels/sources/scopeChainSidebarPane.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2017 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.scope-chain-sidebar-pane-section-header {\n  flex: auto;\n}\n\n.scope-chain-sidebar-pane-section-icon {\n  float: left;\n  margin-right: 5px;\n}\n\n.scope-chain-sidebar-pane-section-subtitle {\n  float: right;\n  margin-left: 5px;\n  max-width: 55%;\n  text-overflow: ellipsis;\n  overflow: hidden;\n}\n\n.scope-chain-sidebar-pane-section-title {\n  font-weight: normal;\n  word-wrap: break-word;\n  white-space: normal;\n}\n\n.scope-chain-sidebar-pane-section {\n  padding: 2px 4px;\n  flex: none;\n}\n\n/*# sourceURL=scopeChainSidebarPane.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);