"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_media_eventDisplayTable_css_js"], {
"./panels/media/eventDisplayTable.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2019 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.no-border-top-datagrid > .data-grid {\n  /* make sure there is no top border, it ruins the menu view */\n  border-top: 0;\n}\n\n.event-display-table-contents-table-container > .widget > .data-grid {\n  height: 100%;\n}\n\n.data-grid .event-display-table-basic-text-table-entry {\n  line-height: 26px;\n}\n\n.event-display-table-contents-json-wrapper > .json-view {\n  overflow: visible;\n}\n\n/*# sourceURL=eventDisplayTable.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);