"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_network_components_EditableSpan_css_js"], {
"./panels/network/components/EditableSpan.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2022 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  display: inline;\n}\n\n.editable {\n  cursor: text;\n  overflow-wrap: anywhere;\n  min-height: 18px;\n  line-height: 18px;\n  min-width: 0.5em;\n  background: transparent;\n  border: none;\n  border-radius: 4px;\n  outline: none;\n  display: inline-block;\n  font-family: var(--monospace-font-family);\n  font-size: var(--monospace-font-size);\n\n  &:hover {\n    border: 1px solid var(--sys-color-neutral-outline);\n  }\n\n  &:focus {\n    border: 1px solid var(--sys-color-state-focus-ring);\n  }\n}\n\n.editable::selection {\n  color: var(--sys-color-on-tonal-container);\n  background-color: var(--sys-color-tonal-container);\n}\n\n/*# sourceURL=EditableSpan.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);