"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_media_playerPropertiesView_css_js"], {
"./panels/media/playerPropertiesView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2019 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.media-attributes-view {\n  border-bottom: 1px solid var(--sys-color-divider);\n}\n\n.media-property-renderer {\n  line-height: 20px;\n  min-height: 28px;\n  padding: 4px 10px;\n  display: block;\n  overflow: hidden;\n\n  &:hover {\n    background: var(--sys-color-state-hover-on-subtle);\n  }\n}\n\n.media-property-renderer:nth-child(even):not(:hover) {\n  background: var(--sys-color-surface1);\n}\n\n.media-property-renderer:has(.json-view) {\n  padding-bottom: 0;\n}\n\n.media-property-renderer:has(.json-view > .expanded) {\n  padding-bottom: 4px;\n}\n\n.media-property-renderer-hidden {\n  display: none;\n}\n\n.media-property-renderer-title {\n  font-size: 12px;\n  float: left;\n  width: 150px;\n}\n\n.media-property-renderer-title::first-letter {\n  text-transform: uppercase;\n}\n\n.media-property-renderer-contents {\n  position: relative;\n\n  & > .json-view {\n    overflow: hidden;\n    padding: 0;\n  }\n}\n\n.media-properties-frame {\n  display: block;\n  overflow-x: hidden;\n}\n\n/*# sourceURL=playerPropertiesView.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);