"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_autofill_autofillView_css_js"], {
"./panels/autofill/autofillView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright (c) 2023 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\nmain {\n  height: 100%;\n}\n\n.placeholder-container {\n  height: calc(100% - 29px);\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}\n\n.placeholder {\n  font-size: 15px;\n  text-align: center;\n}\n\n.address {\n  padding: 10px;\n  margin-right: auto;\n}\n\n.filled-fields-grid {\n  border-top: 1px solid var(--sys-color-divider);\n  box-sizing: border-box;\n}\n\n.content-container {\n  display: flex;\n  flex-flow: column;\n  height: 100%;\n}\n\n.grid-wrapper {\n  flex-grow: 1;\n}\n\n.checkbox-label {\n  display: flex;\n  align-items: center;\n}\n\n.right-to-left {\n  display: flex;\n  flex-flow: row-reverse wrap;\n  justify-content: flex-end;\n}\n\n.label-container {\n  padding: 5px 5px 0;\n  display: flex;\n  align-items: flex-start;\n}\n\n.top-right-corner {\n  display: flex;\n  justify-content: flex-end;\n  padding: 5px;\n}\n\n.matches-filled-field {\n  background-color: var(--sys-color-tonal-container);\n}\n\n.highlighted {\n  background-color: var(--sys-color-state-focus-select);\n}\n\n.link {\n  color: var(--sys-color-primary);\n  text-decoration-line: underline;\n}\n\n.feedback {\n  margin: 1.5px 3px 0 5px;\n}\n\n/*# sourceURL=autofillView.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);