"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_elements_components_cssHintDetailsView_css_js"], {
"./panels/elements/components/cssHintDetailsView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2022 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  padding: 6px;\n}\n\n.hint-popup-wrapper {\n  max-width: 232px;\n  font-size: 12px;\n  line-height: 1.4;\n}\n\ncode {\n  font-weight: bold;\n  font-family: inherit;\n}\n\n.hint-popup-possible-fix {\n  margin-top: 8px;\n}\n\n.clickable {\n  color: var(--sys-color-primary);\n}\n\n.underlined {\n  text-decoration: underline;\n}\n\n.unbreakable-text {\n  white-space: nowrap;\n}\n\n/*# sourceURL=cssHintDetailsView.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);