"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_application_preloading_components_preloadingGrid_css_js-_46ea0"], {
"./panels/application/preloading/components/preloadingGrid.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2022 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  overflow: auto;\n  height: 100%;\n}\n\n.preloading-container {\n  height: 100%;\n  display: flex;\n  flex-direction: column;\n}\n\n.preloading-header {\n  font-size: 15px;\n  background-color: var(--sys-color-cdt-base-container);\n  padding: 1px 4px;\n}\n\n.preloading-placeholder {\n  flex-grow: 1;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  font-size: 13px;\n  color: var(--sys-color-token-subtle);\n}\n\ndevtools-data-grid-controller {\n  border: 1px solid var(--sys-color-divider);\n}\n\n.inline-icon {\n  vertical-align: text-bottom;\n}\n\n/*# sourceURL=preloadingGrid.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);