"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_network_components_RequestHeaderSection_css_js"], {
"./panels/network/components/RequestHeaderSection.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync('/*\n * Copyright 2022 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  display: block;\n}\n\ndevtools-header-section-row:last-of-type {\n  margin-bottom: 10px;\n}\n\ndevtools-header-section-row:first-of-type {\n  margin-top: 2px;\n}\n\n.call-to-action {\n  background-color: var(--sys-color-neutral-container);\n  padding: 8px;\n  border-radius: 5px;\n  margin: 4px;\n}\n\n.call-to-action-body {\n  padding: 6px 0;\n  margin-left: 9.5px;\n  border-left: 2px solid var(--issue-color-yellow);\n  padding-left: 18px;\n  line-height: 20px;\n}\n\n.call-to-action .explanation {\n  font-weight: bold;\n}\n\n.call-to-action code {\n  font-size: 90%;\n}\n\n.call-to-action .example .comment::before {\n  content: " — ";\n}\n\n.link,\n.devtools-link {\n  color: var(--sys-color-primary);\n  text-decoration: underline;\n  cursor: pointer;\n  outline-offset: 2px;\n}\n\n.explanation .link {\n  font-weight: normal;\n}\n\n.inline-icon {\n  vertical-align: middle;\n}\n\n@media (forced-colors: active) {\n  .link,\n  .devtools-link {\n    color: linktext;\n    text-decoration-color: linktext;\n  }\n}\n\n/*# sourceURL=RequestHeaderSection.css */\n');
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);