"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_application_preloading_components_usedPreloadingView_css_js"], {
"./panels/application/preloading/components/usedPreloadingView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2023 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  overflow: auto;\n  height: 100%;\n}\n\nbutton {\n  font-size: inherit;\n}\n\ndevtools-report {\n  padding: 1em 0;\n}\n\ndevtools-report-section-header {\n  padding-bottom: 0;\n  margin-bottom: -1.5em;\n}\n\ndevtools-report-section {\n  min-width: fit-content;\n}\n\ndevtools-report-divider {\n  margin: 1em 0;\n}\n\n.reveal-links {\n  white-space: nowrap;\n}\n\n.link {\n  border: none;\n  background: none;\n  color: var(--sys-color-primary);\n  text-decoration: underline;\n  cursor: pointer;\n  outline-offset: 2px;\n  padding: 0;\n}\n\n.status-badge-container {\n  white-space: nowrap;\n  margin: 8px 0 24px;\n}\n\n.status-badge-container span {\n  margin-right: 2px;\n}\n\n.status-badge {\n  border-radius: 4px;\n  padding: 4px;\n\n  devtools-icon {\n    width: 16px;\n    height: 16px;\n  }\n}\n\n.status-badge-success {\n  background: var(--sys-color-tertiary-container);\n}\n\n.status-badge-failure {\n  background: var(--sys-color-error-container);\n}\n\n.status-badge-neutral {\n  background: var(--sys-color-neutral-container);\n}\n\n/*# sourceURL=usedPreloadingView.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);