"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_settings_components_syncSection_css_js"], {
"./panels/settings/components/syncSection.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright (c) 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  break-inside: avoid;\n  display: block;\n  padding-bottom: 9px;\n  width: 288px;\n}\n\nfieldset {\n  border: 0;\n  margin-left: 20px;\n  padding: 0;\n}\n\nlegend {\n  color: var(--sys-color-token-subtle);\n  font-size: 120%;\n  margin-left: -20px;\n  padding: 0;\n  text-align: left;\n}\n\n.link {\n  color: var(--sys-color-primary);\n  text-decoration: underline;\n  cursor: pointer;\n  outline-offset: 2px;\n}\n\nimg {\n  background-size: 32px 32px;\n  border: 0;\n  border-radius: 50%;\n  display: block;\n  height: 32px;\n  width: 32px;\n}\n\n.warning {\n  display: block;\n  margin-top: 12px;\n}\n\n.account-info {\n  display: flex;\n  align-items: center;\n  margin-top: 12px;\n}\n\n.account-email {\n  display: flex;\n  flex-direction: column;\n  margin-left: 8px;\n}\n\n/*# sourceURL=syncSection.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);