"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_lighthouse_lighthousePanel_css_js"], {
"./panels/lighthouse/lighthousePanel.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2017 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.toolbar {\n  background-color: var(--sys-color-cdt-base-container);\n  border-bottom: 1px solid var(--sys-color-divider);\n}\n\n.lh-root {\n  --report-menu-width: 0;\n\n  user-select: text;\n}\n/* for View Trace button */\n\n.lh-audit-group {\n  position: relative;\n}\n\nbutton.view-trace {\n  margin: 10px;\n}\n\n.lighthouse-results-container {\n  position: relative;\n}\n/** \\'window.opener\\' is null for windows opened from DevTools. This breaks\n    the LH viewer app, so disable this feature. */\n\n.lh-tools--viewer {\n  display: none !important; /* stylelint-disable-line declaration-no-important */\n}\n\n.lighthouse-settings-pane {\n  flex: none;\n}\n\n.lighthouse-settings-pane .toolbar {\n  flex: 1 1;\n}\n\n.lighthouse-toolbar-container {\n  display: flex;\n  flex: none;\n}\n\n.lighthouse-toolbar-container > :first-child {\n  flex: 1 1 auto;\n}\n\n.lh-devtools .lh-element-screenshot__overlay {\n  position: absolute;\n}\n\n/*# sourceURL=lighthousePanel.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);