"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_protocol_monitor_components_toolbar_css_js"], {
"./panels/protocol_monitor/components/toolbar.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2023 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n* {\n  box-sizing: border-box;\n  padding: 0;\n  margin: 0;\n  font-size: inherit;\n}\n\n:host {\n  display: block;\n}\n\n.toolbar {\n  align-items: center;\n  display: flex;\n  justify-content: space-between;\n  padding-left: 5px;\n  padding-right: 10px;\n  padding-top: 1px;\n  height: 27px;\n  background-color: var(--sys-color-cdt-base-container);\n  position: absolute;\n  bottom: 0;\n  width: 100%;\n  border-top: 1px solid var(--sys-color-divider);\n}\n\n.toolbar devtools-button {\n  width: 20px;\n  height: 20px;\n}\n\n/*# sourceURL=toolbar.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);