"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_freestyler_components_provideFeedback_css_js"], {
"./panels/freestyler/components/provideFeedback.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2024 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n* {\n  box-sizing: border-box;\n}\n\n.feedback {\n  display: flex;\n  flex-direction: column;\n  gap: var(--sys-size-4);\n  margin-top: var(--sys-size-4);\n}\n\n.feedback-header {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n}\n\n.feedback-title {\n  margin: 0;\n}\n\n.feedback-disclaimer {\n  padding: 0 var(--sys-size-4);\n}\n\n.vertical-separator {\n  height: 20px;\n  width: 1px;\n  vertical-align: top;\n  margin: 0 var(--sys-size-2);\n  background: var(--color-background-inverted);\n  opacity: 10%;\n  display: inline-block;\n}\n\n/*# sourceURL=./components/provideFeedback.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);