"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_application_openedWindowDetailsView_css_js"], {
"./panels/application/openedWindowDetailsView.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync('/*\n * Copyright 2020 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.report-content-box {\n  overflow: initial;\n}\n\n.report-field-name {\n  flex: 0 0 200px;\n}\n\n.report-field-value {\n  user-select: text;\n  display: flex;\n}\n\n.report-field .inline-name {\n  color: var(--sys-color-state-disabled);\n  padding-left: 2ex;\n  user-select: none;\n  white-space: pre-line;\n}\n\n.report-field .inline-name::after {\n  content: ":\\A0";\n}\n\n.report-field .inline-comment {\n  color: var(--sys-color-token-subtle);\n  padding-left: 1ex;\n  white-space: pre-line;\n}\n\n.report-field .inline-comment::before {\n  content: "(";\n}\n\n.report-field .inline-comment::after {\n  content: ")";\n}\n\n.report-field .inline-span {\n  color: var(--sys-color-token-subtle);\n  padding-left: 1ex;\n  white-space: pre-line;\n}\n\n.report-field-value-link {\n  display: inline-block;\n}\n\n.icon-link.devtools-link {\n  background-color: var(--sys-color-primary);\n  vertical-align: sub;\n}\n\n.frame-details-container {\n  overflow: auto;\n}\n\n.frame-details-report-container {\n  min-width: 550px;\n}\n\n.text-ellipsis {\n  overflow: hidden;\n  text-overflow: ellipsis;\n}\n\n/*# sourceURL=openedWindowDetailsView.css */\n');
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);