"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_elements_platformFontsWidget_css_js"], {
"./panels/elements/platformFontsWidget.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/**\n * Copyright 2016 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  user-select: text;\n}\n\n.platform-fonts {\n  flex-shrink: 0;\n}\n\n.font-usage {\n  color: var(--sys-color-token-subtle);\n  padding-left: 3px;\n}\n\n.title {\n  padding: 0 5px;\n  border-top: 1px solid;\n  border-bottom: 1px solid;\n  border-color: var(--sys-color-divider);\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  height: 24px;\n  background-color: var(--sys-color-surface2);\n  display: flex;\n  align-items: center;\n}\n\n.font-stats-item {\n  padding: 5px 1em;\n\n  div {\n    margin-bottom: 2px;\n  }\n\n  &:not(:last-child) {\n    border-bottom: 1px solid var(--sys-color-divider);\n  }\n}\n\n/*# sourceURL=platformFontsWidget.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);