"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_application_components_badge_css_js"], {
"./panels/application/components/badge.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright (c) 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host .badge-error {\n  --override-adorner-text-color: var(--sys-color-error-bright);\n  --override-adorner-border-color: var(--sys-color-error-bright);\n}\n\n:host .badge-success {\n  --override-adorner-text-color: var(--sys-color-tertiary);\n  --override-adorner-border-color: var(--sys-color-tertiary);\n}\n\n:host .badge-secondary {\n  --override-adorner-text-color: var(--sys-color-token-subtle);\n  --override-adorner-border-color: var(--sys-color-token-subtle);\n}\n\n/* Use mono-space source code font to assist reading of adorner content */\n:host {\n  font-family: var(--source-code-font-family);\n}\n\n/*# sourceURL=badge.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);