"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_application_components_stackTraceRow_css_js"], {
"./panels/application/components/stackTraceRow.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright (c) 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.stack-trace-row {\n  display: flex;\n}\n\n.stack-trace-function-name {\n  width: 100px;\n}\n\n.stack-trace-source-location {\n  display: flex;\n  overflow: hidden;\n}\n\n.text-ellipsis {\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n}\n\n.stack-trace-source-location .text-ellipsis {\n  padding-right: 2px;\n}\n\n.ignore-list-link {\n  opacity: 60%;\n}\n\n.link,\n.devtools-link {\n  color: var(--sys-color-primary);\n  text-decoration: underline;\n  cursor: pointer;\n  outline-offset: 2px;\n  border: none;\n  background: none;\n}\n\n/*# sourceURL=stackTraceRow.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);