"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_elements_components_anchorFunctionLinkSwatch_css_js"], {
"./panels/elements/components/anchorFunctionLinkSwatch.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2024 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.icon-link {\n  color: var(--text-link);\n  width: 13px;\n  height: 13px;\n\n  &:hover {\n    cursor: pointer;\n  }\n}\n\n/*# sourceURL=anchorFunctionLinkSwatch.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);