"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_linear_memory_inspector_components_linearMemoryValueInterpreter_css_js"], {
"./panels/linear_memory_inspector/components/linearMemoryValueInterpreter.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  flex: auto;\n  display: flex;\n}\n\n.value-interpreter {\n  border: 1px solid var(--sys-color-divider);\n  background-color: var(--sys-color-cdt-base-container);\n  overflow: hidden;\n  width: 400px;\n}\n\n.settings-toolbar {\n  min-height: 26px;\n  display: flex;\n  flex-wrap: nowrap;\n  justify-content: space-between;\n  padding-left: 12px;\n  padding-right: 12px;\n  align-items: center;\n}\n\n.settings-toolbar-button {\n  padding: 0;\n  width: 20px;\n  height: 20px;\n  border: none;\n  outline: none;\n  background-color: transparent;\n}\n\n.settings-toolbar-button.active devtools-icon {\n  color: var(--icon-toggled);\n}\n\n.divider {\n  display: block;\n  height: 1px;\n  margin-bottom: 12px;\n  background-color: var(--sys-color-divider);\n}\n\n/*# sourceURL=linearMemoryValueInterpreter.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);