"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_changes_changesSidebar_css_js"], {
"./panels/changes/changesSidebar.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.tree-outline li {\n  min-height: 20px;\n}\n\ndevtools-icon {\n  color: var(--icon-file-default);\n}\n\n.navigator-sm-script-tree-item devtools-icon,\n.navigator-script-tree-item devtools-icon,\n.navigator-snippet-tree-item devtools-icon {\n  color: var(--icon-file-script);\n}\n\n.navigator-sm-stylesheet-tree-item devtools-icon,\n.navigator-stylesheet-tree-item devtools-icon {\n  color: var(--icon-file-styles);\n}\n\n.navigator-image-tree-item devtools-icon {\n  color: var(--icon-file-image);\n}\n\n.navigator-font-tree-item devtools-icon {\n  color: var(--icon-file-font);\n}\n\n.tree-outline li:hover:not(.selected) .selection {\n  display: block;\n\n  & devtools-icon {\n    color: var(--icon-default-hover);\n  }\n}\n\n@media (forced-colors: active) {\n  li,\n  devtools-icon {\n    forced-color-adjust: none;\n    color: ButtonText !important; /* stylelint-disable-line declaration-no-important */\n  }\n}\n\n/*# sourceURL=changesSidebar.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);