"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_recorder_components_stepEditor_css_js"], {
"./panels/recorder/components/stepEditor.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2023 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n* {\n  box-sizing: border-box;\n  padding: 0;\n  margin: 0;\n  font-size: inherit;\n}\n\n:host {\n  display: block;\n}\n\n.row {\n  display: flex;\n  flex-direction: row;\n  color: var(--sys-color-token-property-special);\n  font-family: var(--monospace-font-family);\n  font-size: var(--monospace-font-size);\n  align-items: center;\n  line-height: 18px;\n  margin-top: 3px;\n}\n\n.row devtools-button {\n  line-height: 1;\n  margin-left: 0.5em;\n}\n\n.separator {\n  margin-right: 0.5em;\n  color: var(--sys-color-on-surface);\n}\n\n.padded {\n  margin-left: 2em;\n}\n\n.padded.double {\n  margin-left: 4em;\n}\n\n.selector-picker {\n  width: 18px;\n  height: 18px;\n}\n\n.inline-button {\n  width: 18px;\n  height: 18px;\n  opacity: 0%;\n  visibility: hidden;\n  transition: opacity 200ms;\n  flex-shrink: 0;\n}\n\n.row:focus-within .inline-button,\n.row:hover .inline-button {\n  opacity: 100%;\n  visibility: visible;\n}\n\n.wrapped.row {\n  flex-wrap: wrap;\n}\n\n.gap.row {\n  gap: 5px;\n}\n\n.gap.row devtools-button {\n  margin-left: 0;\n}\n\n.regular-font {\n  font-family: inherit;\n  font-size: inherit;\n}\n\n.no-margin {\n  margin: 0;\n}\n\n.row-buttons {\n  margin-top: 3px;\n}\n\n.error {\n  margin: 3px 0 6px;\n  padding: 8px 12px;\n  background: var(--sys-color-error-container);\n  color: var(--sys-color-error);\n}\n\n/*# sourceURL=stepEditor.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);