"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["panels_linear_memory_inspector_components_linearMemoryInspector_css_js"], {
"./panels/linear_memory_inspector/components/linearMemoryInspector.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  flex: auto;\n  display: flex;\n}\n\n.view {\n  width: 100%;\n  display: flex;\n  flex: 1;\n  flex-direction: column;\n  font-family: var(--monospace-font-family);\n  font-size: var(--monospace-font-size);\n  padding: 9px 12px 9px 7px;\n}\n\ndevtools-linear-memory-inspector-viewer {\n  justify-content: center;\n}\n\ndevtools-linear-memory-inspector-navigator + devtools-linear-memory-inspector-viewer {\n  margin-top: 12px;\n}\n\n.value-interpreter {\n  display: flex;\n}\n\n/*# sourceURL=linearMemoryInspector.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);