"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["third_party_marked_package_lib_marked_esm_d_ts"], {
"./third_party/marked/package/lib/marked.esm.d.ts": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  Hooks: function() { return _Hooks; },
  Lexer: function() { return _Lexer; },
  Parser: function() { return _Parser; },
  Renderer: function() { return _Renderer; },
  TextRenderer: function() { return _TextRenderer; },
  Tokenizer: function() { return _Tokenizer; },
  defaults: function() { return _defaults; },
  getDefaults: function() { return _getDefaults; }
});
// Generated by dts-bundle-generator v9.5.1



}),

}]);