"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_components_markdown_view_MarkdownView_d_ts"], {
"./ui/components/markdown_view/MarkdownView.d.ts": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
/**
 * Renderer used in Console Insights and Freestyler for the text generated by an LLM.
 */ 


}),

}]);