"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_components_report_view_reportSectionHeader_css_js"], {
"./ui/components/report_view/reportSectionHeader.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  grid-column-start: span 2;\n}\n\n.section-header {\n  padding: 12px;\n  margin-left: 18px;\n  display: flex;\n  flex-direction: row;\n  align-items: center;\n  flex: auto;\n  text-overflow: ellipsis;\n  overflow: hidden;\n  font-weight: bold;\n  color: var(--sys-color-on-surface);\n  user-select: none;\n}\n\n/*# sourceURL=reportSectionHeader.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);