"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_components_expandable_list_expandableList_css_js"], {
"./ui/components/expandable_list/expandableList.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  overflow: hidden;\n}\n\ndiv {\n  line-height: 1.7em;\n}\n\n.arrow-icon-button {\n  cursor: pointer;\n  padding: 1px 0;\n  border: none;\n  background: none;\n  margin-right: 2px;\n}\n\n.arrow-icon {\n  display: inline-block;\n  mask-image: var(--image-file-triangle-right);\n  background-color: var(--icon-default);\n  margin-top: 2px;\n  height: 14px;\n  width: 14px;\n  transition: transform 200ms;\n}\n\n.arrow-icon.expanded {\n  transform: rotate(90deg);\n}\n\n.expandable-list-container {\n  display: flex;\n  margin-top: 4px;\n}\n\n.expandable-list-items {\n  overflow: hidden;\n}\n\n.link,\n.devtools-link {\n  color: var(--sys-color-primary);\n  text-decoration: underline;\n  cursor: pointer;\n  outline-offset: 2px;\n}\n\nbutton.link {\n  border: none;\n  background: none;\n  font-family: inherit;\n  font-size: inherit;\n}\n\n.text-ellipsis {\n  overflow: hidden;\n  text-overflow: ellipsis;\n  white-space: nowrap;\n}\n\n/*# sourceURL=expandableList.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);