"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_components_markdown_view_codeBlock_css_js"], {
"./ui/components/markdown_view/codeBlock.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2023 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}\n\ncode {\n  color: var(--sys-color-on-surface);\n  font-size: 11px;\n  user-select: text;\n  cursor: text;\n  background: var(--sys-color-surface1);\n}\n\n.codeblock {\n  margin-bottom: 8px;\n  box-sizing: border-box;\n  border-radius: 4px;\n  background-color: var(--sys-color-surface5);\n  color: var(--sys-color-on-surface);\n}\n\n.codeblock .toolbar {\n  box-sizing: border-box;\n  display: flex;\n  height: 28px;\n  flex-direction: row;\n  padding: 0 11px;\n  font-size: 11px;\n  font-style: normal;\n  font-weight: 400;\n  line-height: 16px;\n}\n\n.codeblock .editor-wrapper {\n  color: var(--sys-color-on-surface);\n  background: var(--sys-color-surface1);\n  padding: 10px 5px;\n}\n\n.codeblock .lang {\n  padding: 6px 0;\n  flex: 1;\n}\n\n.codeblock .copy {\n  padding: 4px 0;\n  align-items: center;\n  display: flex;\n}\n\n.codeblock .copy-button {\n  margin: 0;\n  padding: 0;\n  background: transparent;\n  border: none;\n  font-size: 11px;\n  line-height: 16px;\n  display: flex;\n  flex-direction: row;\n  align-items: center;\n  gap: 4px;\n}\n\n.codeblock .copy-button.copied {\n  color: var(--sys-color-primary);\n\n  --copy-icon-color: var(--sys-color-primary);\n}\n\n.notice {\n  margin-top: 3px;\n  margin-left: 3px;\n\n  .link {\n    color: var(--sys-color-primary);\n    text-decoration-line: underline;\n  }\n}\n\n/*# sourceURL=codeBlock.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);