"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_components_highlighting_highlighting_css_js"], {
"./ui/components/highlighting/highlighting.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2023 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n/* stylelint-disable-next-line selector-pseudo-element-no-unknown,selector-type-no-unknown */\n:root::highlight(search-highlight) {\n  background-color: var(--sys-color-yellow-outline);\n}\n\n/*# sourceURL=highlighting.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);