"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_components_survey_link_surveyLink_css_js"], {
"./ui/components/survey_link/surveyLink.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.link-icon {\n  vertical-align: sub;\n  margin-right: 0.5ch;\n}\n\n.link {\n  padding: var(--issue-link-padding, 4px 0 0 0);\n  text-decoration: var(--issue-link-text-decoration, underline);\n  cursor: pointer;\n  font-size: var(--issue-link-font-size, 14px);\n  color: var(--sys-color-primary);\n  outline-offset: 2px;\n  border: none;\n  background: none;\n  font-family: inherit;\n}\n\n.link:focus:not(:focus-visible) {\n  outline: none;\n}\n\n.pending-link {\n  opacity: 75%;\n  pointer-events: none;\n  cursor: default;\n  text-decoration: none;\n}\n\n.disabled-link {\n  pointer-events: none;\n  cursor: default;\n  text-decoration: none;\n}\n\n/*# sourceURL=surveyLink.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);