"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_legacy_emptyWidget_css_js-_75021"], {
"./ui/legacy/emptyWidget.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright (c) 2015 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.empty-bold-text {\n  display: block;\n  font-size: 1.5em;\n  margin: 0.83em 0;\n  font-weight: bold;\n}\n\n.empty-view {\n  color: var(--sys-color-token-subtle);\n  padding: 30px;\n  text-align: center;\n  min-width: 70px;\n}\n\n.empty-view-scroller {\n  justify-content: center;\n  overflow: auto;\n}\n\n.empty-view p {\n  white-space: initial;\n  line-height: 18px;\n  max-width: 300px;\n  flex-shrink: 0;\n}\n\n/*# sourceURL=emptyWidget.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);