"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_legacy_components_inline_editor_colorSwatch_css_js"], {
"./ui/legacy/components/inline_editor/colorSwatch.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright (c) 2015 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  white-space: nowrap;\n}\n\n.color-swatch {\n  position: relative;\n  margin-left: 1px;\n  margin-right: 2px;\n  width: 12px;\n  height: 12px;\n  transform: scale(0.8);\n  vertical-align: -2px;\n  display: inline-block;\n  user-select: none;\n  background-image: var(--image-file-checker);\n  line-height: 10px;\n}\n\n.color-swatch-inner {\n  width: 100%;\n  height: 100%;\n  display: inline-block;\n  border: 1px solid var(--sys-color-neutral-outline);\n  box-sizing: border-box;\n  cursor: pointer;\n}\n\n.color-swatch.readonly .color-swatch-inner {\n  cursor: unset;\n}\n\n.color-swatch:not(.readonly) .color-swatch-inner:hover {\n  border: 1px solid var(--sys-color-outline);\n}\n\n@media (forced-colors: active) {\n  .color-swatch {\n    forced-color-adjust: none;\n  }\n}\n\n/*# sourceURL=colorSwatch.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);