"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_legacy_components_inline_editor_bezierSwatch_css_js"], {
"./ui/legacy/components/inline_editor/bezierSwatch.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync("/*\n * Copyright 2016 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n:host {\n  white-space: nowrap;\n}\n\ndevtools-icon.bezier-swatch-icon {\n  position: relative;\n  transform: scale(0.7);\n  margin: -5px -2px -3px -4px;\n  user-select: none;\n  color: var(--icon-css);\n  cursor: default;\n}\n\ndevtools-icon.bezier-swatch-icon:hover {\n  color: var(--icon-css-hover);\n}\n\n/*# sourceURL=bezierSwatch.css */\n");
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);