"use strict";
(self['webpackChunk'] = self['webpackChunk'] || []).push([["ui_legacy_components_inline_editor_cssLength_css_js"], {
"./ui/legacy/components/inline_editor/cssLength.css.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  "default": function() { return __WEBPACK_DEFAULT_EXPORT__; }
});
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */ var styles = new CSSStyleSheet();
styles.replaceSync('/*\n * Copyright 2021 The Chromium Authors. All rights reserved.\n * Use of this source code is governed by a BSD-style license that can be\n * found in the LICENSE file.\n */\n\n.css-length {\n  display: inline-block;\n  position: relative;\n  outline: none;\n}\n\n.css-length.overloaded {\n  text-decoration: line-through;\n}\n\n.value {\n  cursor: ew-resize;\n}\n\n.icon {\n  position: absolute;\n  display: inline-block;\n  mask-image: var(--image-file-chevron-down);\n  mask-repeat: no-repeat;\n  background-color: var(--icon-default);\n  transform: scale(0.7);\n  margin-left: -7px;\n  margin-top: -3px;\n  content: "";\n  height: 2em;\n  width: 2em;\n}\n\n:host(:not(:last-child)) {\n  margin-right: 0.1em;\n}\n\n/*# sourceURL=cssLength.css */\n');
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


}),

}]);