"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_animation_AnimationScreenshotPopover_js"],{

/***/ "./panels/animation/AnimationScreenshotPopover.js":
/*!********************************************************!*\
  !*** ./panels/animation/AnimationScreenshotPopover.js ***!
  \********************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   AnimationScreenshotPopover: () => (/* binding */ AnimationScreenshotPopover)
/* harmony export */ });
/* harmony import */ var _ui_legacy_legacy_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../../ui/legacy/legacy.js */ "./ui/legacy/legacy.js");
/* harmony import */ var _animationScreenshotPopover_css_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./animationScreenshotPopover.css.js */ "./panels/animation/animationScreenshotPopover.css.js");
// Copyright (c) 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


class AnimationScreenshotPopover extends _ui_legacy_legacy_js__WEBPACK_IMPORTED_MODULE_0__.Widget.VBox {
    #frames;
    #rafId;
    #currentFrame;
    #progressBar;
    #showFrame;
    #endDelay;
    constructor(images) {
        super(true);
        console.assert(images.length > 0);
        this.contentElement.classList.add('animation-screenshot-popover');
        this.#frames = images;
        for (const image of images) {
            this.contentElement.appendChild(image);
            image.style.display = 'none';
        }
        this.#rafId = 0;
        this.#currentFrame = 0;
        this.#frames[0].style.display = 'block';
        this.#progressBar = this.contentElement.createChild('div', 'animation-progress');
    }
    wasShown() {
        this.#rafId = this.contentElement.window().requestAnimationFrame(this.changeFrame.bind(this));
        this.registerCSSFiles([_animationScreenshotPopover_css_js__WEBPACK_IMPORTED_MODULE_1__["default"]]);
    }
    willHide() {
        this.contentElement.window().cancelAnimationFrame(this.#rafId);
        this.#endDelay = undefined;
    }
    changeFrame() {
        this.#rafId = this.contentElement.window().requestAnimationFrame(this.changeFrame.bind(this));
        if (this.#endDelay) {
            this.#endDelay--;
            return;
        }
        this.#showFrame = !this.#showFrame;
        if (!this.#showFrame) {
            return;
        }
        const numFrames = this.#frames.length;
        this.#frames[this.#currentFrame % numFrames].style.display = 'none';
        this.#currentFrame++;
        this.#frames[(this.#currentFrame) % numFrames].style.display = 'block';
        if (this.#currentFrame % numFrames === numFrames - 1) {
            this.#endDelay = 50;
        }
        this.#progressBar.style.width = (this.#currentFrame % numFrames + 1) / numFrames * 100 + '%';
    }
}
//# sourceMappingURL=AnimationScreenshotPopover.js.map

/***/ }),

/***/ "./panels/animation/animationScreenshotPopover.css.js":
/*!************************************************************!*\
  !*** ./panels/animation/animationScreenshotPopover.css.js ***!
  \************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright (c) 2015 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

img {
  max-height: 300px;
  border-radius: 2px;
}

.animation-progress {
  position: absolute;
  height: 2px;
  bottom: 0;
  left: 0;
  background: var(--legacy-selection-bg-color);
}

/*# sourceURL=animationScreenshotPopover.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);