"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_elements_layersWidget_css_js"],{

/***/ "./panels/elements/layersWidget.css.js":
/*!*********************************************!*\
  !*** ./panels/elements/layersWidget.css.js ***!
  \*********************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/**
 * Copyright 2022 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.styles-layers-pane {
  overflow: hidden;
  padding-left: 2px;
  background-color: var(--sys-color-cdt-base-container);
  border-bottom: 1px solid var(--sys-color-divider);
  margin-top: 0;
  padding-bottom: 2px;
}

.styles-layers-pane > div {
  font-weight: bold;
  margin: 8px 4px 6px;
}

.styles-layers-pane > table {
  width: 100%;
  border-spacing: 0;
}

.styles-layers-pane td {
  padding: 0;
}

/*# sourceURL=layersWidget.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);