"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_network_components_RequestTrustTokensView_css_js"],{

/***/ "./panels/network/components/RequestTrustTokensView.css.js":
/*!*****************************************************************!*\
  !*** ./panels/network/components/RequestTrustTokensView.css.js ***!
  \*****************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2021 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */
.code {
  font-family: var(--monospace-font-family);
  font-size: var(--monospace-font-size);
}

.issuers-list {
  display: flex;
  flex-direction: column;
  list-style-type: none;
  padding: 0;
  margin: 0;
}

.status-icon {
  margin: 0 0.3em 2px 0;
  vertical-align: middle;
}

/*# sourceURL=RequestTrustTokensView.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);