"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_elements_components_adornerSettingsPane_css_js"],{

/***/ "./panels/elements/components/adornerSettingsPane.css.js":
/*!***************************************************************!*\
  !*** ./panels/elements/components/adornerSettingsPane.css.js ***!
  \***************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2021 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.adorner-settings-pane {
  display: flex;
  height: auto;
  padding: 6px 12px;
  color: var(--sys-color-on-surface);
  font-size: 12px;
  align-items: center;
}

.settings-title {
  font-weight: 500;
  margin-right: 6px;
}

.setting {
  margin-left: 1em;
}

.adorner-status {
  margin: auto 0.4em auto 0;
}

.adorner-status,
.adorner-name {
  vertical-align: middle;
}

/*# sourceURL=adornerSettingsPane.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);