"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_css_overview_cssOverviewProcessingView_css_js"],{

/***/ "./panels/css_overview/cssOverviewProcessingView.css.js":
/*!**************************************************************!*\
  !*** ./panels/css_overview/cssOverviewProcessingView.css.js ***!
  \**************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/**
 * Copyright 2019 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.overview-processing-view {
  overflow: hidden;
  padding: 16px;
  justify-content: center;
  align-items: center;
  height: 100%;
}

.overview-processing-view h1 {
  font-size: 16px;
  text-align: center;
  font-weight: normal;
  margin: 0;
  padding: 8px;
}

.overview-processing-view h2 {
  font-size: 12px;
  text-align: center;
  font-weight: normal;
  margin: 0;
  padding-top: 32px;
}

/*# sourceURL=cssOverviewProcessingView.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);