"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_sources_scopeChainSidebarPane_css_js"],{

/***/ "./panels/sources/scopeChainSidebarPane.css.js":
/*!*****************************************************!*\
  !*** ./panels/sources/scopeChainSidebarPane.css.js ***!
  \*****************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2017 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.scope-chain-sidebar-pane-section-header {
  flex: auto;
}

.scope-chain-sidebar-pane-section-icon {
  float: left;
  margin-right: 5px;
}

.scope-chain-sidebar-pane-section-subtitle {
  float: right;
  margin-left: 5px;
  max-width: 55%;
  text-overflow: ellipsis;
  overflow: hidden;
}

.scope-chain-sidebar-pane-section-title {
  font-weight: normal;
  word-wrap: break-word;
  white-space: normal;
}

.scope-chain-sidebar-pane-section {
  padding: 2px 4px;
  flex: none;
}

/*# sourceURL=scopeChainSidebarPane.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);