"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_emulation_deviceModeToolbar_css_legacy_js"],{

/***/ "./panels/emulation/deviceModeToolbar.css.legacy.js":
/*!**********************************************************!*\
  !*** ./panels/emulation/deviceModeToolbar.css.legacy.js ***!
  \**********************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ({
  cssContent: `/*
 * Copyright 2015 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.device-mode-x {
  margin: 0 1px;
  font-size: 16px;
}

.device-mode-empty-toolbar-element {
  width: 0;
}

/*# sourceURL=deviceModeToolbar.css */
`
});


/***/ })

}]);