"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_elements_components_cssPropertyDocsView_css_js"],{

/***/ "./panels/elements/components/cssPropertyDocsView.css.js":
/*!***************************************************************!*\
  !*** ./panels/elements/components/cssPropertyDocsView.css.js ***!
  \***************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2023 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  padding: 6px;
}

.docs-popup-wrapper {
  max-width: 350px;
  font-size: 12px;
  line-height: 1.4;
}

.docs-popup-section {
  margin-top: 8px;
}

.clickable {
  color: var(--sys-color-primary);
}

.underlined {
  text-decoration: underline;
}

.unbreakable-text {
  white-space: nowrap;
}

.footer {
  display: flex;
  justify-content: space-between;
}

.dont-show input {
  vertical-align: bottom;
}

/*# sourceURL=cssPropertyDocsView.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);