"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_explain_components_consoleInsightSourcesList_css_js"],{

/***/ "./panels/explain/components/consoleInsightSourcesList.css.js":
/*!********************************************************************!*\
  !*** ./panels/explain/components/consoleInsightSourcesList.css.js ***!
  \********************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2023 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

* {
  padding: 0;
  margin: 0;
  box-sizing: border-box;
}

:host {
  display: block;
}

ul {
  color: var(--sys-color-primary);
  font-size: 12px;
  font-style: normal;
  font-weight: 400;
  line-height: 18px;
  margin-top: 8px;
}

li {
  list-style-type: none;
}

ul .link {
  color: var(--sys-color-primary);
  display: inline-flex !important; /* stylelint-disable-line declaration-no-important */
  align-items: center;
  gap: 4px;
  text-decoration-line: underline;
}

devtools-icon {
  height: 16px;
  width: 16px;
}

devtools-icon[name="open-externally"] {
  color: var(--icon-link);
}

.source-disclaimer {
  color: var(--sys-color-on-surface-subtle);
}

/*# sourceURL=./components/consoleInsightSourcesList.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);