"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_network_networkManageCustomHeadersView_css_js"],{

/***/ "./panels/network/networkManageCustomHeadersView.css.js":
/*!**************************************************************!*\
  !*** ./panels/network/networkManageCustomHeadersView.css.js ***!
  \**************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2016 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.custom-headers-list {
  height: 272px;
  width: 250px;
}

.custom-headers-wrapper {
  margin: 10px;
}

.header {
  padding: 0 0 6px;
  font-size: 18px;
  font-weight: normal;
  flex: none;
}

.custom-headers-header {
  padding: 2px;
}

.custom-headers-list-item {
  padding-left: 5px;
}

.editor-container {
  padding: 5px 0 0 5px;
}

.add-button {
  width: 150px;
  margin: auto;
  margin-top: 5px;
}

/*# sourceURL=networkManageCustomHeadersView.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);