"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_linear_memory_inspector_components_linearMemoryValueInterpreter_css_js"],{

/***/ "./panels/linear_memory_inspector/components/linearMemoryValueInterpreter.css.js":
/*!***************************************************************************************!*\
  !*** ./panels/linear_memory_inspector/components/linearMemoryValueInterpreter.css.js ***!
  \***************************************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2021 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  flex: auto;
  display: flex;
}

.value-interpreter {
  border: 1px solid var(--sys-color-divider);
  background-color: var(--sys-color-cdt-base-container);
  overflow: hidden;
  width: 400px;
}

.settings-toolbar {
  min-height: 26px;
  display: flex;
  flex-wrap: nowrap;
  justify-content: space-between;
  padding-left: 12px;
  padding-right: 12px;
  align-items: center;
}

.settings-toolbar-button {
  padding: 0;
  width: 20px;
  height: 20px;
  border: none;
  outline: none;
  background-color: transparent;
}

.settings-toolbar-button.active devtools-icon {
  color: var(--icon-toggled);
}

.divider {
  display: block;
  height: 1px;
  margin-bottom: 12px;
  background-color: var(--sys-color-divider);
}

/*# sourceURL=linearMemoryValueInterpreter.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);