"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_network_requestHTMLView_css_js"],{

/***/ "./panels/network/requestHTMLView.css.js":
/*!***********************************************!*\
  !*** ./panels/network/requestHTMLView.css.js ***!
  \***********************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright (c) 2018 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.html-preview-frame {
  box-shadow: var(--drop-shadow);
  /* We always want a white background, even in dark mode */
  background: var(--ref-palette-neutral100);
  flex-grow: 1;
  margin: 20px;
}

/*# sourceURL=requestHTMLView.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);