"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_animation_animationScreenshotPopover_css_js"],{

/***/ "./panels/animation/animationScreenshotPopover.css.js":
/*!************************************************************!*\
  !*** ./panels/animation/animationScreenshotPopover.css.js ***!
  \************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright (c) 2015 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

img {
  max-height: 300px;
  border-radius: 2px;
}

.animation-progress {
  position: absolute;
  height: 2px;
  bottom: 0;
  left: 0;
  background: var(--legacy-selection-bg-color);
}

/*# sourceURL=animationScreenshotPopover.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);