"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_sources_breakpointEditDialog_css_js"],{

/***/ "./panels/sources/breakpointEditDialog.css.js":
/*!****************************************************!*\
  !*** ./panels/sources/breakpointEditDialog.css.js ***!
  \****************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2018 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

:host {
  z-index: 30;
  padding: 4px;
  background-color: var(--sys-color-surface3);
  border-radius: 7px;
  border: 2px solid var(--sys-color-divider);
  width: 90%;
  pointer-events: auto;
}

:host(.sources-edit-breakpoint-dialog) {
  border-radius: 0;
  z-index: 30;
  background-color: var(--sys-color-surface3);
  width: 555px;
  pointer-events: auto;
  margin-left: -1px;
  padding: 0 10px 10px 5px;
  border: 1px solid var(--sys-color-divider);
}

:host-context(.sources-edit-breakpoint-dialog) .condition-editor {
  background-color: var(--sys-color-cdt-base-container);
  margin: 0 6px 20px 3px;
}

:host-context(.sources-edit-breakpoint-dialog) .source-frame-breakpoint-toolbar {
  font-family: sans-serif;
  font-size: 12px;
}

:host-context(.sources-edit-breakpoint-dialog) .link,
.devtools-link {
  font-family: sans-serif;
  font-size: 12px;
  margin: 0 3px;
}

:host-context(.sources-edit-breakpoint-dialog) devtools-icon.link-icon {
  vertical-align: sub;
  margin-right: 0.5ch;
  color: var(--icon-link);
  width: 16px;
  height: 16px;
}

:host-context(.sources-edit-breakpoint-dialog) .link-wrapper {
  display: inline-flex;
}

:host-context(.sources-edit-breakpoint-dialog) .dialog-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

:host-context(.sources-edit-breakpoint-dialog) .dialog-header > devtools-icon:hover {
  color: var(--icon-default-hover);
}

/*# sourceURL=breakpointEditDialog.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);