"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_protocol_monitor_protocolMonitor_css_js"],{

/***/ "./panels/protocol_monitor/protocolMonitor.css.js":
/*!********************************************************!*\
  !*** ./panels/protocol_monitor/protocolMonitor.css.js ***!
  \********************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2021 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.protocol-monitor .protocol-monitor-toolbar {
  border-bottom: 1px solid var(--sys-color-divider);
}

.protocol-monitor .protocol-monitor-bottom-toolbar {
  border-top: 1px solid var(--sys-color-divider);
}

/*# sourceURL=protocolMonitor.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);