"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_elements_elementStatePaneWidget_css_js"],{

/***/ "./panels/elements/elementStatePaneWidget.css.js":
/*!*******************************************************!*\
  !*** ./panels/elements/elementStatePaneWidget.css.js ***!
  \*******************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/**
 * Copyright 2017 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.styles-element-state-pane {
  overflow: hidden;
  padding-left: 2px;
  background-color: var(--sys-color-cdt-base-container);
  border-bottom: 1px solid var(--sys-color-divider);
  margin-top: 0;
  padding-bottom: 2px;
}

.styles-element-state-pane > .page-state-checkbox {
  margin-block: 6px;
  display: flex;
  align-items: center;
  gap: 2px;
}

.styles-element-state-pane > .section-header {
  margin: 8px 4px 6px;
  color: var(--color-text-secondary);
}

.styles-element-state-pane > table {
  width: 100%;
  border-spacing: 0;
}

.styles-element-state-pane td {
  padding: 0;
}

/*# sourceURL=elementStatePaneWidget.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);