"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_recorder_components_startView_css_js"],{

/***/ "./panels/recorder/components/startView.css.js":
/*!*****************************************************!*\
  !*** ./panels/recorder/components/startView.css.js ***!
  \*****************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2023 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-weight: normal;
  font-size: inherit;
}

:host {
  flex: 1;
  display: block;
  overflow: auto;
}

.wrapper {
  padding: 24px;
  background-color: var(--sys-color-cdt-base-container);
  height: 100%;
  display: flex;
  flex-direction: column;
}

.fit-content {
  width: fit-content;
}

.align-right {
  width: auto;
  display: flex;
  flex-direction: row;
  justify-content: flex-end;
}

/*# sourceURL=startView.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);