"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["panels_application_cookieItemsView_css_js"],{

/***/ "./panels/application/cookieItemsView.css.js":
/*!***************************************************!*\
  !*** ./panels/application/cookieItemsView.css.js ***!
  \***************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2019 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.cookie-preview-widget {
  padding: 2px 6px;
}

.cookie-preview-widget-header {
  font-weight: bold;
  user-select: none;
  white-space: nowrap;
  margin-bottom: 4px;
  flex: 0 0 18px;
  display: flex;
  align-items: center;
}

.cookie-preview-widget-header-label {
  line-height: 18px;
}

.cookie-preview-widget-cookie-value {
  user-select: text;
  word-break: break-all;
  flex: 1;
  overflow: auto;
}

.cookie-preview-widget-toggle {
  margin-left: 12px;
  font-weight: normal;
}

/*# sourceURL=cookieItemsView.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);