(self["webpackChunkrspack_repro"] = self["webpackChunkrspack_repro"] || []).push([["src_third_party_marked_package_lib_marked_d_cts"],{

/***/ "./src/third_party/marked/package/lib/marked.d.cts":
/*!*********************************************************!*\
  !*** ./src/third_party/marked/package/lib/marked.d.cts ***!
  \*********************************************************/
/***/ (() => {

throw new Error("Module parse failed: Unexpected token (3:7)\nYou may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n| // Generated by dts-bundle-generator v9.5.1\n| \n> export type MarkedToken = (Tokens.Space | Tokens.Code | Tokens.Heading | Tokens.Table | Tokens.Hr | Tokens.Blockquote | Tokens.List | Tokens.ListItem | Tokens.Paragraph | Tokens.HTML | Tokens.Text | Tokens.Def | Tokens.Escape | Tokens.Tag | Tokens.Image | Tokens.Link | Tokens.Strong | Tokens.Em | Tokens.Codespan | Tokens.Br | Tokens.Del);\n| export type Token = (MarkedToken | Tokens.Generic);\n| export declare namespace Tokens {");

/***/ })

}]);