"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["ui_components_highlighting_highlighting_css_js"],{

/***/ "./ui/components/highlighting/highlighting.css.js":
/*!********************************************************!*\
  !*** ./ui/components/highlighting/highlighting.css.js ***!
  \********************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2023 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/* stylelint-disable-next-line selector-pseudo-element-no-unknown,selector-type-no-unknown */
:root::highlight(search-highlight) {
  background-color: var(--sys-color-yellow-outline);
}

/*# sourceURL=highlighting.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);