"use strict";
(self["webpackChunk"] = self["webpackChunk"] || []).push([["ui_components_two_states_counter_twoStatesCounter_css_js"],{

/***/ "./ui/components/two_states_counter/twoStatesCounter.css.js":
/*!******************************************************************!*\
  !*** ./ui/components/two_states_counter/twoStatesCounter.css.js ***!
  \******************************************************************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => (__WEBPACK_DEFAULT_EXPORT__)
/* harmony export */ });
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
const styles = new CSSStyleSheet();
styles.replaceSync(
`/*
 * Copyright 2022 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

.active.split {
  border-radius: 50% 0% 0% 50%;
}

.inactive.split {
  border-radius: 0% 50% 50% 0%;
}

.counter {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}

.part {
  display: flex;
  border-radius: 50%;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

.active {
  color: var(--sys-color-on-primary);
  background-color: var(--sys-color-primary);
}

.inactive {
  color: var(--sys-color-state-disabled);
  background-color: var(--sys-color-state-disabled-container);
}

/*# sourceURL=twoStatesCounter.css */
`);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (styles);


/***/ })

}]);